name: MADE Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  made-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: Install Python dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r project/requirement.txt  # Replace with the path to your requirements file
              
      - name: Run MADE Pipeline
        run: 
            bash project/pipeline.sh 